# Generated by Django 6.0.7 on 2026-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=50)),
                ('cupos', models.IntegerField()),
            ],
        ),
    ]
