# Generated by Django 6.1 on 2026-08-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyecto', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('ALTA', 'Alta'), ('MEDIA', 'Media')], default='MEDIA', max_length=5)),
                ('estado', models.CharField(choices=[('PROCESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente')], default='PROCESO', max_length=15)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestor_proyecto.proyecto')),
            ],
        ),
    ]
