# Generated by Django 6.1 on 2026-08-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyecto', '0003_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('MEDIA', 'Media'), ('ALTA', 'Alta'), ('BAJA', 'Baja')], default='MEDIA', max_length=5),
        ),
    ]
