# Generated by Django 6.1 on 2026-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyecto', '0004_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='img/Logo.png', upload_to='img/'),
        ),
    ]
